@extends('layouts.app')
@section('title', 'Administration')
@section('content')
<div class="min-h-[calc(100vh-16rem)] bg-gradient-to-b from-beige-50 to-white py-10">
 <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
  <section class="relative overflow-hidden rounded-3xl bg-charcoal px-7 py-8 text-white shadow-xl sm:px-10">
   <div class="absolute -right-12 -top-16 h-56 w-56 rounded-full bg-gold/15"></div>
   <div class="relative flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-gold">Espace sécurisé</p><h1 class="mt-3 text-3xl font-extrabold sm:text-4xl">Bonjour, Administrateur</h1><p class="mt-2 text-white/70">Pilotez les utilisateurs, les annonces et les catégories.</p></div><nav class="flex flex-wrap gap-2"><a href="{{ route('admin.annonces') }}" class="rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-charcoal hover:bg-gold">Annonces</a><a href="{{ route('admin.users') }}" class="rounded-xl border border-white/20 bg-white/10 px-4 py-2.5 text-sm font-bold hover:bg-white/20">Utilisateurs</a><a href="{{ route('admin.type-biens') }}" class="rounded-xl border border-white/20 bg-white/10 px-4 py-2.5 text-sm font-bold hover:bg-white/20">Catégories</a></nav></div>
  </section>
  @php($cards = [['Utilisateurs','utilisateurs','bg-blue-500'],['Propriétaires','proprietaires','bg-violet-500'],['Acheteurs / Locataires','acheteurs','bg-emerald-500'],['Annonces publiées','validees','bg-gold-dark'],['À traiter','en_attente','bg-amber-500'],['Annonces refusées','refusees','bg-rose-500'],['Vues cumulées','vues','bg-cyan-500'],['Messages échangés','messages','bg-indigo-500']])
  <section class="mt-8"><p class="section-label">Vue d’ensemble</p><h2 class="mt-2 text-2xl font-extrabold text-charcoal">Les chiffres clés</h2><div class="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($cards as [$label,$key,$color])<article class="rounded-2xl border border-beige-100 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div class="flex items-start justify-between"><div><p class="text-sm font-semibold text-charcoal/60">{{ $label }}</p><p class="mt-2 text-3xl font-extrabold text-charcoal">{{ number_format($stats[$key],0,',',' ') }}</p></div><span class="h-3 w-3 rounded-full {{ $color }}"></span></div><p class="mt-4 border-t border-beige-100 pt-3 text-xs text-charcoal/50">Statistique mise à jour en temps réel</p></article>@endforeach</div></section>
  <section class="mt-8 grid gap-5 lg:grid-cols-3"><div class="rounded-2xl border border-beige-100 bg-white p-6 shadow-sm lg:col-span-2"><p class="section-label">Modération</p><div class="mt-2 flex flex-wrap items-center justify-between gap-3"><h2 class="text-xl font-extrabold text-charcoal">Publications à examiner</h2><span class="rounded-full bg-amber-100 px-3 py-1 text-sm font-bold text-amber-700">{{ $stats['en_attente'] }} en attente</span></div><p class="mt-3 text-sm text-charcoal/60">Validez ou refusez les annonces avant leur publication.</p><a href="{{ route('admin.annonces', ['statut' => 'en_attente']) }}" class="btn-primary mt-5 px-5 py-2.5">Examiner les annonces</a></div><div class="rounded-2xl border border-gold/40 bg-gold/15 p-6"><p class="section-label">Gestion rapide</p><h2 class="mt-2 text-xl font-extrabold text-charcoal">Catégories de biens</h2><p class="mt-3 text-sm text-charcoal/65">Organisez les types de logements disponibles.</p><a href="{{ route('admin.type-biens') }}" class="mt-5 inline-block text-sm font-bold text-charcoal hover:text-gold-dark">Gérer les catégories →</a></div></section>
 </div>
</div>
@endsection
